---
title: Змагання з веслування
hero_image: images/small_banner.png
description: Зробіть змагання з веслування, в якиих ви повинні уникати перешкод.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: жовтий
listed: true
ingredient: false
copyedit: true
curriculum: 1, дизайн-0, програмування-1, фізичні обчислення-0, виробництво-0, спільноти-0
duration: 2
interests: ігри
technology: scratch
site_areas: проекти
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 01.01.2017
steps:
  - 
    title: Вступ
  - 
    title: Вам потрібно
  - 
    title: Розпочнемо
  - 
    title: Контроль човна
  - 
    title: Аварія
  - 
    title: 'Challenge: перемога!'
  - 
    title: 'Вимкнути звукові ефекти'
  - 
    title: Час судового розгляду
  - 
    title: Перешкоди і бонуси
  - 
    title: 'Challenge: більше перешкод!'
  - 
    title: 'Challenge: більше човнів!'
  - 
    title: 'Challenge: більше рівнів!'
