---
title: Boot race
hero_image: images/small_banner.png
description: Maak een bootrace-spel waarin je obstakels moet ontwijken.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Wat heb je nodig
  - 
    title: Aan de slag
  - 
    title: De boot besturen
  - 
    title: Botsen
  - 
    title: 'Uitdaging: winnen!'
    challenge: true
  - 
    title: 'Uitdaging: geluidseffecten'
  - 
    title: Tijd bijhouden
  - 
    title: 'Obstakels en bonussen'
    challenge: true
  - 
    title: 'Uitdaging: meer obstakels!'
