---
title: Boot race
hero_image: images/small_banner.png
description: Maak een bootrace-spel waarin je obstakels moet ontwijken.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Inleiding
  - 
    title: Aan de slag
  - 
    title: De boot besturen
  - 
    title: Botsen!
  - 
    title: Botsen
  - 
    title: 'Challenge: geluidseffecten'
    challenge: true
  - 
    title: Een meting toevoegen
  - 
    title: Tijd bijhouden
  - 
    title: 'Obstakels en bonussen'
    challenge: true
  - 
    title: Wat nu?
