title: Boat Race
hero_image: images/small_banner.png
description: Use Scratch to make a boat race game
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: cc-prototype
listed: false
ingredient: false
duration: 2
interests: "games"
technology: "scratch"
steps:
  - title: Introduction
  - title: "What you'll need"
  - title: Getting started
  - title: Controlling the boat
  - title: Crashing
  - title: "Challenge: Winning!"
  - title: "Challenge: Sound effects"
  - title: Time trial
  - title: Obstacles and power ups
  - title: "Challenge: More obstacles!"
  - title: "Challenge: More boats!"
  - title: "Challenge: More levels!"
