title: Boat Race
hero_image: images/small_banner.png
description: Make a boat race game in which you have to avoid obstacles.
listed: true
copyedit: true
version: 4.1.0
last_tested: 2018-09-20
steps: 
- title: Introduction
- title: Getting started
- title: Controlling the boat
- title: Crashing
- title: Winning!
- title: 'Challenge: sound effects'
- title: Time trial
- title: Obstacles and power ups
- title: 'Challenge: more obstacles!'
- title: 'Challenge: more boats!'
- title: 'Challenge: more levels!'
- title: What Next?