---
title: ボートレース
hero_image: images/small_banner.png
description: このプロジェクトではプログラミングを使ったゲームを作ります。マウスを使ってボートをゴールの島まで動かしましょう！
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: はじめに
  - 
    title: まずはじめに
  - 
    title: ボートの制御
  - 
    title: クラッシュ！
  - 
    title: Winning!
  - 
    title: 'チャレンジ：音をならす'
    challenge: true
  - 
    title: タイマーを追加する
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
