---
title: Đua thuyền
hero_image: images / small_banner.png
description: Thực hiện một trò chơi đua thuyền, trong đó bạn phải tránh chướng ngại vật.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: màu vàng
listed: true
ingredient: false
copyedit: true
curriculum: 1, thiết kế-0, lập trình-1, phys-comp-0, sản xuất-0, cộng đồng-0
duration: 2
interests: Trò chơi
technology: vết trầy
site_areas: dự án
technologies: vết trầy
hardware: ''
software: vết trầy
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn cần
  - 
    title: Bắt đầu
  - 
    title: Kiểm soát thuyền
  - 
    title: Đâm
  - 
    title: 'Thách thức: chiến thắng!'
  - 
    title: 'Thách thức: hiệu ứng âm thanh'
  - 
    title: Thời gian thử nghiệm
  - 
    title: Trở ngại và up sức mạnh
  - 
    title: 'Thách thức: nhiều trở ngại!'
  - 
    title: 'Thách thức: nhiều thuyền hơn!'
  - 
    title: 'Thách thức: nhiều cấp độ hơn!'
