---
title: Đua thuyền
hero_image: images/small_banner.png
description: Tạo một trò chơi đua thuyền trong đó bạn phải tránh chướng ngại vật
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Giới thiệu
  - 
    title: Bắt đầu
  - 
    title: Điều khiển thuyền
  - 
    title: Va chạm!
  - 
    title: Chiến thắng!
  - 
    title: 'Thử thách: hiệu ứng âm thanh'
    challenge: true
  - 
    title: Thêm một bộ đếm thời gian
  - 
    title: Chướng ngại vật và tên lửa đẩy
  - 
    title: 'Thách thức: cải thiện trò chơi của bạn'
    challenge: true
  - 
    title: Bước tiếp theo?
