---
title: Đua thuyền
hero_image: images/small_banner.png
description: Tạo một trò chơi đua thuyền, trong đó bạn phải tránh chướng ngại vật.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: màu vàng
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: trò chơi
technology: scratch
site_areas: dự án
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Bắt đầu
  - 
    title: Điều khiển chiếc thuyền
  - 
    title: Va chạm
  - 
    title: 'Thử thách: chiến thắng!'
  - 
    title: 'Thử thách: hiệu ứng âm thanh'
  - 
    title: Tính giờ
  - 
    title: Chướng ngại vật và tăng tốc
  - 
    title: 'Thử thách: nhiều chướng ngại vật hơn!'
  - 
    title: 'Thử thách: nhiều thuyền hơn!'
  - 
    title: 'Thử thách: nhiều cấp độ hơn!'
