---
title: Bådsejlads
hero_image: images/small_banner.png
description: Du skal lære hvordan du laver et spil, hvor man bruger musen til at styre en båd til en øde ø.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Bådsejlads
  - 
    title: Getting started
  - 
    title: Controlling the boat
  - 
    title: Crashing!
  - 
    title: Winning!
  - 
    title: 'Challenge: sound effects'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
