---
title: Bådsejlads
hero_image: images/small_banner.png
description: Du skal lære hvordan du laver et spil, hvor man bruger musen til at styre en båd til en øde ø.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: gul
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: spil
technology: scratch
site_areas: projekter
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017/01/01
steps:
  - 
    title: Bådsejlads
  - 
    title: Hvad du har brug for
  - 
    title: Kom i gang
  - 
    title: Styring af båden
  - 
    title: Sammenstød
  - 
    title: 'Challenge: winning!'
  - 
    title: 'Challenge: sound effects'
  - 
    title: Time trial
  - 
    title: Obstacles and power ups
  - 
    title: 'Challenge: more obstacles!'
  - 
    title: 'Challenge: more boats!'
  - 
    title: 'Challenge: more levels!'
