---
title: Utrka brodovima
hero_image: images/small_banner.png
description: U ovom projektu naučit ćeš napraviti igricu u kojoj ćeš mišem dovesti brod do pustog otoka.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Getting started
  - 
    title: Controlling the boat
  - 
    title: Crashing!
  - 
    title: Winning!
  - 
    title: 'Challenge: sound effects'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
