---
title: Utrka brodovima
hero_image: images/small_banner.png
description: U ovom projektu naučit ćeš napraviti igricu u kojoj ćeš mišem dovesti brod do pustog otoka.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Početak
  - 
    title: Upravljanje brodom
  - 
    title: Sudaranje!
  - 
    title: Winning!
  - 
    title: 'Izazov: zvučni efekti'
    challenge: true
  - 
    title: Dodavanje mjerača vremena
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
