---
title: Utrka brodovima
hero_image: images/small_banner.png
description: Kreiraj igru utrka brodovima u kojoj moraš izbjegavati prepreke.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: žuta
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: games
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Potrebno je
  - 
    title: Početak
  - 
    title: Upravljanje brodom
  - 
    title: Razbijanje broda
  - 
    title: 'Izazov: Pobjeda!'
  - 
    title: 'Izazov: zvučni efekti'
  - 
    title: Vremensko ograničenje
  - 
    title: Prepreke i poboljšanja
  - 
    title: 'Izazov: više prepreka!'
  - 
    title: 'Izazov: više brodova!'
  - 
    title: 'Izazov: više razina igre!'
