---
title: Vene kilpa-ajo
hero_image: images/small_banner.png
description: Luo vene kilpa-ajo peli, jossa sinun on väistettävä esteitä
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Esittely
  - 
    title: Näin pääset alkuun
  - 
    title: Veneen ohjaaminen
  - 
    title: Törmääminen!
  - 
    title: Voittaminen!
  - 
    title: 'Haaste: äänitehosteet'
    challenge: true
  - 
    title: Ajastimen lisääminen
  - 
    title: Esteet ja lisävoimia
  - 
    title: 'Haaste: pelin kehittäminen'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
