---
title: Vene kilpailu
hero_image: Kuvien / small_banner.png
description: Tee venekilpailupeli, jossa sinun on vältettävä esteitä.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: keltainen
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, ohjelmointi-1, phys-comp-0, valmistus-0, yhteisö-0
duration: 2
interests: pelit
technology: naarmu
site_areas: hankkeet
technologies: naarmu
hardware: ''
software: naarmu
version: 4
last_tested: 01.1.2017
steps:
  - 
    title: esittely
  - 
    title: Mitä tarvitset
  - 
    title: Päästä alkuun
  - 
    title: Veneen ohjaaminen
  - 
    title: kaatuu
  - 
    title: 'Haaste: voittaa!'
  - 
    title: 'Haaste: äänitehosteet'
  - 
    title: Aikakokeilu
  - 
    title: Esteet ja teho
  - 
    title: 'Haaste: enemmän esteitä!'
  - 
    title: 'Haaste: lisää veneitä!'
  - 
    title: 'Haaste: enemmän tasoja!'
