---
title: Carrera de Barcos
hero_image: images/small_banner.png
description: Haz un juego de carreras de barcos en el que tendrás que evitar obstáculos.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Primeros pasos
  - 
    title: Controlando el barco
  - 
    title: '¡Chocando!'
  - 
    title: Chocando
  - 
    title: 'Desafío: efectos de sonido'
    challenge: true
  - 
    title: Añadir un temporizador
  - 
    title: Prueba de contrarreloj
  - 
    title: 'Obstáculos y poderes'
    challenge: true
  - 
    title: 'Desafío: más colores'
