---
title: Ras Cwch
hero_image: images/small_banner.png
description: Byddwn yn creu gêm i hwylio cwch at ynys yng nghanol y môr.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Dechrau'r prosiect
  - 
    title: Rheoli'r cwch
  - 
    title: Llongddrylliad!
  - 
    title: 'Her: Ennill!'
  - 
    title: 'Her: Effeithiau sain'
    challenge: true
  - 
    title: Ras yn erbyn amser
  - 
    title: Rhwystrau a chyflymu'r cwch
  - 
    title: 'Her: Mwy o rwystrau!'
    challenge: true
  - 
    title: 'Her: Mwy o gychod!'
