---
title: Ras Gwch
hero_image: images/small_banner.png
description: Creu gêm am rasio cwch gan osgoi rhwystrau.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: yellow
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: games
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Beth sydd eu hangen
  - 
    title: Sut i ddechrau
  - 
    title: Rheoli'r cwch
  - 
    title: Dryllio
  - 
    title: 'Her: ennill!'
  - 
    title: 'Her: effeithiau sain'
  - 
    title: Treial amser
  - 
    title: 'Her: Mwy o rwystrau!'
  - 
    title: 'Her: Mwy o gychod!'
  - 
    title: 'Her: Mwy o lefelau!'
  - 
    title: 'Her: Mwy o lefelau!'
