---
title: Carrera de Barcos
hero_image: images/small_banner.png
description: Haz un juego de carreras de barcos en el que tendrás que evitar obstáculos.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: amarillo
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: juegos
technology: scratch
site_areas: proyectos
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Primeros pasos
  - 
    title: Controlando el barco
  - 
    title: Chocando
  - 
    title: 'Challenge: ¡ganando!'
  - 
    title: 'Desafío: efectos de sonido'
  - 
    title: Contrarreloj
  - 
    title: Obstáculos y poderes
  - 
    title: 'Desafío: ¡más obstáculos!'
  - 
    title: 'Desafío: ¡más barcos!'
  - 
    title: 'Desafío: ¡más niveles!'
