---
title: Bootsrennen
hero_image: images/small_banner.png
description: Programmiere ein Rennspiel, in dem Du mit deinem Boot Hindernissen ausweichen musst.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Einleitung
  - 
    title: Was du brauchen wirst
  - 
    title: Erste Schritte
  - 
    title: Das Boot steuern
  - 
    title: Einen Unfall bauen
  - 
    title: 'Herausforderung: Gewinnen!'
    challenge: true
  - 
    title: 'Herausforderung: Soundeffekte'
  - 
    title: Zeitfahren
  - 
    title: 'Hindernisse und Power-ups'
    challenge: true
  - 
    title: 'Herausforderung: Noch mehr Hindernisse!'
