---
title: Boat Race
hero_image: images/small_banner.png
description: Vei învăța cum să creezi un joc în care vei utiliza mouse-ul ca să navighezi o barcă înspre o insulă pustie.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Boat Race
  - 
    title: Getting started
  - 
    title: Controlling the boat
  - 
    title: Crashing!
  - 
    title: Winning!
  - 
    title: 'Challenge: sound effects'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
