---
title: Corrida de barco
hero_image: images/small_banner.png
description: Você vai aprender a fazer um jogo, no qual você usará o mouse para navegar um barco até uma ilha deserta.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: Começando
  - 
    title: Controlando o barco
  - 
    title: Batendo!
  - 
    title: Ganhando!
  - 
    title: 'Desafio: efeitos sonoros'
    challenge: true
  - 
    title: Adicionando um cronômetro
  - 
    title: Obstáculos e aceleradores
  - 
    title: 'Desafio: melhore seu jogo'
    challenge: true
  - 
    title: Teste-se
  - 
    title: O que vem depois?
