---
title: بوٹ ریس
hero_image: تصاویر / small_banner.png
description: ایک کشتی ریس کھیل بنائیں جس میں آپ کو رکاوٹوں سے بچنے کی ضرورت ہے.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race؟redirect=false
theme: پیلا
listed: true
ingredient: false
copyedit: true
curriculum: 1، ڈیزائن-0، پروگرامنگ -1، فیز-کمپ-0، تیاری-0، کمیونٹی-0
duration: 2
interests: کھیل
technology: خرگوش
site_areas: منصوبوں
technologies: خرگوش
hardware: ''
software: خرگوش
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: تعارف
  - 
    title: آپ کو کیا ضرورت ہے
  - 
    title: شروع ہوا چاہتا ہے
  - 
    title: کشتی کو کنٹرول کرنا
  - 
    title: کرشنگ
  - 
    title: 'چیلنج: جیت!'
  - 
    title: 'چیلنج: صوتی اثرات'
  - 
    title: وقت کی آزمائش
  - 
    title: رکاوٹوں اور طاقت اپ
  - 
    title: 'چیلنج: زیادہ رکاوٹوں!'
  - 
    title: 'چیلنج: زیادہ کشتیاں!'
  - 
    title: 'چیلنج: زیادہ سطح!'
