---
title: Balap perahu
hero_image: images / small_banner.png
description: Buat game balap perahu di mana Anda harus menghindari rintangan
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: pengantar
  - 
    title: Mulai
  - 
    title: Mengontrol perahu
  - 
    title: Menabrak!
  - 
    title: Kemenangan!
  - 
    title: 'Tantangan: efek suara'
    challenge: true
  - 
    title: Menambahkan penghitung waktu
  - 
    title: Hambatan dan pemacu
  - 
    title: 'Tantangan: meningkatkan permainan Anda'
    challenge: true
  - 
    title: Apa selanjutnya?
