---
title: Čolnarjenje
hero_image: images/small_banner.png
description: Naredite dirko, v kateri se morate s čolnom izogibati oviram.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: yellow
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: games
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Kaj boste potrebovali
  - 
    title: Začnite
  - 
    title: Nadziranje čolna
  - 
    title: Trčenje
  - 
    title: 'Izziv: Zmagovalec'
  - 
    title: 'Izziv: Zvočni učinki'
  - 
    title: Čas
  - 
    title: Ovire in posebni učinki
  - 
    title: 'Izziv: Več ovir!'
  - 
    title: 'Izziv: Več čolnov!'
  - 
    title: 'Izziv: Več stopenj!'
