---
title: Čolnarjenje
hero_image: images/small_banner.png
description: Naredite dirko, v kateri se morate s čolnom izogibati oviram.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: rumeno
listed: true
ingredient: false
copyedit: true
curriculum: ustvarjalec, design-0, programiranje-2, fiz-comp-0, izdelava-0, skupnost-0
duration: 2
interests: igre
technology: praska
site_areas: kodeklub, praska
steps:
  - 
    title: Uvod
  - 
    title: Kaj boste potrebovali
  - 
    title: Začetek
  - 
    title: Nadziranje čolna
  - 
    title: Zlom
  - 
    title: 'Izziv: zmagovalec!'
  - 
    title: 'Izziv: zvočni učinki'
  - 
    title: Časovni poskus
  - 
    title: Ovire in moči
  - 
    title: 'Izziv: več ovir!'
  - 
    title: 'Izziv: več čolnov!'
  - 
    title: 'Izziv: več ravni!'

