---
title: Závod lodí
hero_image: images/small_banner.png
description: Naučíš se jak vytvořit hru, ve které budeš používat myš k navigaci loďky na opuštěný ostrov.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: yellow
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: hry
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Závod lodí
  - 
    title: Co budeš potřebovat
  - 
    title: Začínáme
  - 
    title: Ovládání lodi
  - 
    title: Havárie
  - 
    title: 'Výzva: vítězství!'
  - 
    title: 'Výzva: zvukové efekty'
  - 
    title: Závod na čas
  - 
    title: Překážky a bonusy
  - 
    title: 'Výzva: další překážky!'
  - 
    title: 'Výzva: více lodí!'
  - 
    title: 'Výzva: více úrovní!'
