---
title: Závod lodí
hero_image: images/small_banner.png
description: Vytvoř hru, ve které se závodící lodi budou vyhýbat překážkám.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: yellow
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
duration: 2
interests: hry
technology: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Úvod
  - 
    title: Co budeš potřebovat
  - 
    title: Začínáme
  - 
    title: Ovládání lodi
  - 
    title: Havárie
  - 
    title: 'Výzva: vítězství!'
  - 
    title: 'Výzva: zvukové efekty'
  - 
    title: Závod na čas
  - 
    title: Obstacles and power ups
  - 
    title: 'Challenge: more obstacles!'
  - 
    title: 'Challenge: more boats!'
  - 
    title: 'Challenge: more levels!'

