---
title: סירת מרוץ
hero_image: images/small_banner.png
description: תה הולך ללמוד איך ליצור משחק, שבו אתה תשתמש בעכבר כדי לנווט סירה לאי בודד.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: סירת מרוץ
  - 
    title: Getting started
  - 
    title: Controlling the boat
  - 
    title: Crashing!
  - 
    title: Winning!
  - 
    title: 'Challenge: sound effects'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
