---
title: סירת מרוץ
hero_image: images/small_banner.png
description: תה הולך ללמוד איך ליצור משחק, שבו אתה תשתמש בעכבר כדי לנווט סירה לאי בודד.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: נאבד בחלל
  - 
    title: מתחילים
  - 
    title: שליטה בסירה
  - 
    title: התרסקות!
  - 
    title: לנצח!
  - 
    title: 'אתגר: אפקטים קוליים'
    challenge: true
  - 
    title: הוספת טיימר
  - 
    title: מכשולים ומאיצים
  - 
    title: 'האתגר: שיפור המשחק שלך'
    challenge: true
  - 
    title: מה הלאה?
