---
title: מירוץ סירות
hero_image: images/small_banner.png
description: הכן משחק מירוץ סירות שבו צריך להמנע ממכשולים
listed: true
copyedit: true
version: 4.1.2
last_tested: 20-09-2018
steps:
  - 
    title: הקדמה
  - 
    title: מתחילים
  - 
    title: שליטה בסירה
  - 
    title: התרסקות!
  - 
    title: לנצח!
  - 
    title: 'אתגר: אפקטים קוליים'
    challenge: true
  - 
    title: הוספת מד זמן
  - 
    title: מכשולים ומאיצים
  - 
    title: 'האתגר: שיפור המשחק שלך'
    challenge: true
  - 
    title: What next?
