---
title: Hajóverseny
hero_image: images / small_banner.png
description: Hozzon létre egy hajóverseny-játékot, amelyben el kell kerülnie az akadályokat
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018/09/20
steps:
  - 
    title: Bevezetés
  - 
    title: Elkezdeni
  - 
    title: A hajó irányítása
  - 
    title: Összeomlik!
  - 
    title: Nyerő!
  - 
    title: 'Kihívás: hanghatások'
    challenge: true
  - 
    title: Időzítő hozzáadása
  - 
    title: Akadályok és erősítők
  - 
    title: 'Kihívás: a játék fejlesztése'
    challenge: true
  - 
    title: Mi a következő?
