---
title: Hajóverseny
hero_image: images / small_banner.png
description: Hajtson végre egy hajóverseny játékot, amelyben el kell kerülnie az akadályokat.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: sárga
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programozás-1, phys-comp-0, gyártás-0, community-0
duration: 2
interests: játékok
technology: karcolás
site_areas: projektek
technologies: karcolás
hardware: ''
software: karcolás
version: 4
last_tested: 2017/01/01
steps:
  - 
    title: Bevezetés
  - 
    title: Amire szükséged lesz
  - 
    title: Elkezdeni
  - 
    title: A hajó ellenőrzése
  - 
    title: összeomlik
  - 
    title: 'Kihívás: győztes!'
  - 
    title: 'Kihívás: hanghatások'
  - 
    title: Időfutam
  - 
    title: Akadályok és teljesítménynövelések
  - 
    title: 'Kihívás: több akadály!'
  - 
    title: 'Kihívás: több csónak!'
  - 
    title: 'Kihívás: több szint!'
