---
title: 划船比賽
hero_image: images/small_banner.png
description: 創建一個遊艇比賽，你必須避免障礙
listed: true
copyedit: true
version: 4.1.2
last_tested: 二零一八年九月二十零日
steps:
  - 
    title: 介紹
  - 
    title: 入門
  - 
    title: 控制船
  - 
    title: 崩潰！
  - 
    title: 贏了！
  - 
    title: '挑戰：聲音效果'
    challenge: true
  - 
    title: 添加計時器
  - 
    title: 障礙和助推器
  - 
    title: '挑戰：改善你的遊戲'
    challenge: true
  - 
    title: 接下來是什麼？
