---
title: Carrera de barcos
hero_image: images/small_banner.png
description: Vas a aprender cómo crear un juego en el que usarás el ratón para navegar con tu barco hasta una isla desierta.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Carrera de barcos
  - 
    title: Getting started
  - 
    title: Controlling the boat
  - 
    title: Crashing!
  - 
    title: Winning!
  - 
    title: 'Challenge: sound effects'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
