---
title: Boat race
hero_image: images/small_banner.png
description: Create a boat-racing game in which you have to avoid obstacles
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: المقدمة
  - 
    title: الشروع في البدء
  - 
    title: التحكم في القارب
  - 
    title: الاصطدام!
  - 
    title: Winning!
  - 
    title: 'التحدي: المؤثرات الصوتية'
    challenge: true
  - 
    title: إضافة مؤقت
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
