---
title: Boat race
hero_image: images/small_banner.png
description: Create a boat-racing game in which you have to avoid obstacles
listed: true
copyedit: true
version: 4.1.2
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 시작하기
  - 
    title: 배 조종하기
  - 
    title: 충돌!
  - 
    title: Winning!
  - 
    title: '도전과제: 음향 효과'
    challenge: true
  - 
    title: 타이머 추가하기
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: '도전과제: 더 많은 연필들'
