---
title: Wyścig łodzi
hero_image: images/small_banner.png
description: Naucz się, jak stworzyć grę, w której będziesz kierować łodzią, żeby omijać przeszkody
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Zaczynamy
  - 
    title: Sterowanie łodzią
  - 
    title: Zderzenia!
  - 
    title: Zwycięski!
  - 
    title: 'Wyzwanie: efekty dźwiękowe'
    challenge: true
  - 
    title: Dodawanie licznika czasu
  - 
    title: Przeszkody i przyspieszacze
  - 
    title: 'Wyzwanie: ulepszanie gry'
    challenge: true
  - 
    title: Sprawdź się
  - 
    title: Co dalej?
