---
title: Wyścig łodzi
hero_image: images/small_banner.png
description: Naucz się, jak stworzyć grę, w której będziesz kierować łodzią.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Zaczynamy
  - 
    title: Sterowanie łodzią
  - 
    title: Zderzenia!
  - 
    title: Zwycięski!
  - 
    title: 'Wyzwanie: efekty dźwiękowe'
    challenge: true
  - 
    title: Dodawanie timera
  - 
    title: Przeszkody i boostery
  - 
    title: 'Wyzwanie: ulepszanie gry'
    challenge: true
  - 
    title: Sprawdź się
  - 
    title: Co dalej?
