---
title: Wyścig łodzi
hero_image: images/small_banner.png
description: Naucz się, jak stworzyć grę, w której będziesz kierować łodzią.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Życzenia urodzinowe
  - 
    title: Zaczynamy
  - 
    title: Sterowanie łodzią
  - 
    title: Zderzenia!
  - 
    title: Winning!
  - 
    title: 'Wyzwanie: efekty dźwiękowe'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: Co następne?
