---
title: Preteky lodí
hero_image: images/small_banner.png
description: V tomto projekte sa naučíš ako vytvoriť hru, v ktorej budeš použitím myši navigovať loďku na pustý ostrov.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Preteky lodí
  - 
    title: Getting started
  - 
    title: Controlling the boat
  - 
    title: Crashing!
  - 
    title: Winning!
  - 
    title: 'Challenge: sound effects'
    challenge: true
  - 
    title: Adding a timer
  - 
    title: Obstacles and boosters
  - 
    title: 'Challenge: improving your game'
    challenge: true
  - 
    title: What next?
