---
title: Perlumbaan bot
hero_image: imej / small_banner.png
description: Buat permainan perlumbaan bot di mana anda perlu mengelakkan halangan
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: Pengenalan
  - 
    title: Bermula
  - 
    title: Mengawal perahu
  - 
    title: Crashing!
  - 
    title: Memenangi!
  - 
    title: 'Cabaran: kesan bunyi'
    challenge: true
  - 
    title: Menambah pemasa
  - 
    title: Halangan dan penggalak
  - 
    title: 'Cabaran: meningkatkan permainan anda'
    challenge: true
  - 
    title: Test yourself
  - 
    title: What next?
