---
title: Perlumbaan bot
hero_image: imej / small_banner.png
description: Buat permainan perlumbaan bot di mana anda perlu mengelakkan halangan.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: kuning
listed: true
ingredient: false
copyedit: true
curriculum: 1, reka bentuk-0, pengaturcaraan-1, phys-comp-0, pembuatan-0, komuniti-0
duration: 2
interests: permainan
technology: awal
site_areas: projek
technologies: awal
hardware: ''
software: awal
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Pengenalan
  - 
    title: Apa yang anda perlukan
  - 
    title: Bermula
  - 
    title: Mengawal perahu
  - 
    title: Crashing
  - 
    title: 'Cabaran: memenangi!'
  - 
    title: 'Cabaran: kesan bunyi'
  - 
    title: Percubaan masa
  - 
    title: Halangan dan kuasa naik
  - 
    title: 'Cabaran: lebih banyak halangan!'
  - 
    title: 'Cabaran: lebih banyak bot!'
  - 
    title: 'Cabaran: lebih banyak tahap!'
