---
title: নৌকা জাতি
hero_image: images/small_banner.png
description: একটি নৌকা-রেসিং খেলা তৈরি করুন যা আপনাকে বাধাগুলি এড়াতে হবে
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: পরিচিতি
  - 
    title: শুরু করুন
  - 
    title: নৌকা নিয়ন্ত্রণ
  - 
    title: বিপর্যয়!
  - 
    title: বিজয়ী!
  - 
    title: 'Challenge: সাউন্ড ইফেক্ট'
    challenge: true
  - 
    title: সময়-সংরক্ষককে যোগ করা
  - 
    title: বাধা এবং boosters
  - 
    title: 'চ্যালেঞ্জ: আপনার খেলা উন্নতি'
    challenge: true
  - 
    title: তারপর কি?
