---
title: Trka brodova
hero_image: images/small_banner.png
description: Napravi igru trke brodova u kojoj moraš da izbjegavaš prepreke.
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Početni koraci
  - 
    title: Upravljanje brodom
  - 
    title: Sudaranje!
  - 
    title: Sudaranje
  - 
    title: 'Izazov: zvučni efekti'
    challenge: true
  - 
    title: Dodavanje mjerača vremena
  - 
    title: Mjerenje vremena
  - 
    title: 'Prepreke i prednosti'
    challenge: true
  - 
    title: 'Izazov: više prepreka!'
