---
title: Course de bateaux
hero_image: images/small_banner.png
description: Apprends à programmer un jeu de bateau!
original_url: https://projects.raspberrypi.org/en/projects/boat-race
theme: jaune
listed: true
ingredient: false
copyedit: true
curriculum: creator, design-0, programming-2, phys-comp-0, manufacture-0, community-0
duration: 2
interests: jeux
technology: scratch
site_areas: codeclub, scratch
steps:
  - 
    title: Introduction
  - 
    title: Planifier votre jeu
  - 
    title: Direction du bateau
  - 
    title: Collision!
  - 
    title: 'Défi : Victoire!'
  - 
    title: 'Défi : Effets sonores'
  - 
    title: Course contre la montre
  - 
    title: Obstacles et difficulté
  - 
    title: 'Défi : Plus d''obstacles!'
  - 
    title: 'Défi : Plus de bateaux!'
  - 
    title: 'Défi : Plus de niveaux!'
  - 
    title: 'Challenge: more levels!'

