---
title: Course de bateaux
hero_image: images/small_banner.png
description: Apprends à programmer un jeu de bateau!
listed: true
copyedit: true
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Pour commencer
  - 
    title: Contrôler le bateau
  - 
    title: Collision!
  - 
    title: 'Défi : Victoire!'
  - 
    title: 'Défi: effets sonores'
    challenge: true
  - 
    title: Ajouter un chronomètre
  - 
    title: Obstacles et difficulté
  - 
    title: 'Défi : Plus d''obstacles!'
    challenge: true
  - 
    title: 'Défi : plus de crayons'
