---
title: Course de bateaux
hero_image: images/small_banner.png
description: Apprends à programmer un jeu de bateau.
original_url: https://projects.raspberrypi.org/en/projects/boat-race
theme: jaune
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
duration: 2
interests: jeux
technology: scratch
site_areas: projects
technologies: scratch
hardware: ''
software: scratch
version: 4
last_tested: 2017-01-01
steps:
  - 
    title: Introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Pour commencer
  - 
    title: Contrôler le bateau
  - 
    title: Collision
  - 
    title: 'Challenge: gagner!'
  - 
    title: 'Challenge: effets sonores'
  - 
    title: Course contre la montre
  - 
    title: Obstacles et puissances
  - 
    title: 'Challenge: plus d''obstacles!'
  - 
    title: 'Challenge: plus de bateaux!'
  - 
    title: 'Challenge: plus de niveaux!'
