---
title: බෝට්ටු තරඟය
hero_image: images/small_banner.png
description: බාධක වළක්වා ගනිමින් ගමන් ගත යුතු බෝට්ටු-තරඟ(boat-racing) ක්‍රීඩාවක් සෑදීම
listed: true
copyedit: true
version: 4.1.2
last_tested: 2018-09-20
steps:
  - 
    title: හැදින්වීම
  - 
    title: ආරම්භ කරන්න
  - 
    title: බෝට්ටුව පාලනය කිරීම
  - 
    title: හැප්පීම!
  - 
    title: ජයග්‍රහනය!
  - 
    title: 'අභියෝගය: ශබ්ද(sound) ප්‍රයෝග(effects)'
    challenge: true
  - 
    title: ටයිමරයක්(timer එකක්) එක් කිරීම
  - 
    title: බාධක(obstacles) සහ බූස්ටර(boosters)
  - 
    title: 'අභියෝගය: ඔබේ ක්‍රීඩාව වැඩි දියුණු කිරීම'
    challenge: true
  - 
    title: ඔබම පරීක්ෂා කරගන්න
  - 
    title: ඊලඟට කුමක්ද?
