---
title: Tekne yarışı
hero_image: images / small_banner.png
description: Engellerden kaçınmanız gereken bir tekne yarışı oyunu yapın.
original_url: https://www.codeclubprojects.org/en-GB/scratch/boat-race?redirect=false
theme: Sarı
listed: true
ingredient: false
copyedit: true
curriculum: 1, tasarım-0, programlama-1, fiz-comp-0, üretim-0, topluluk-0
duration: 2
interests: oyunlar
technology: çizik
site_areas: projeler
technologies: çizik
hardware: ''
software: çizik
version: 4
last_tested: 2017/01/01
steps:
  - 
    title: Giriş
  - 
    title: Neye ihtiyacınız olacak?
  - 
    title: Başlamak
  - 
    title: Tekneyi kontrol etmek
  - 
    title: ezmeye
  - 
    title: 'Meydan okuma: kazanma!'
  - 
    title: 'Meydan okuma: ses efektleri'
  - 
    title: Deneme süresi
  - 
    title: Engeller ve güç ups
  - 
    title: 'Zorluk: Daha fazla engel!'
  - 
    title: 'Zorluk: Daha fazla tekne!'
  - 
    title: 'Zorluk: Daha fazla seviye!'
